# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
